// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGA_dIViPg5I26Dsp37OiChKqcE_FdQLw',
    appId: '1:1036205428938:android:8c62d61c13fab89368e433',
    messagingSenderId: '1036205428938',
    projectId: 'premed-mobile-app',
    storageBucket: 'premed-mobile-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWA_0B_UQfFxxy5mZI12Cft2UcHPyKshU',
    appId: '1:1036205428938:ios:726b278a19fe5af868e433',
    messagingSenderId: '1036205428938',
    projectId: 'premed-mobile-app',
    storageBucket: 'premed-mobile-app.appspot.com',
    androidClientId: '1036205428938-1lut6otfpqao28jqggefhs9h3qe3tl27.apps.googleusercontent.com',
    iosClientId: '1036205428938-6j376eu97ju537p3h23lm3o2s4n97na4.apps.googleusercontent.com',
    iosBundleId: 'com.premedpk.iOSMobileApp',
  );
}
