export const countryPhoneCodes = [
  "+1",
  "+7",
  "+20",
  "+27",
  "+30",
  "+31",
  "+32",
  "+33",
  "+34",
  "+36",
  "+39",
  "+40",
  "+41",
  "+43",
  "+44",
  "+45",
  "+46",
  "+47",
  "+48",
  "+49",
  "+51",
  "+52",
  "+53",
  "+54",
  "+55",
  "+56",
  "+57",
  "+58",
  "+60",
  "+61",
  "+62",
  "+63",
  "+64",
  "+65",
  "+66",
  "+81",
  "+82",
  "+84",
  "+86",
  "+90",
  "+91",
  "+92",
  "+93",
  "+94",
  "+95",
  "+98",
  "+212",
  "+213",
  "+216",
  "+218",
  "+220",
  "+221",
  "+222",
  "+223",
  "+224",
  "+225",
  "+226",
  "+227",
  "+228",
  "+229",
  "+230",
  "+231",
  "+232",
  "+233",
  "+234",
  "+235",
  "+236",
  "+237",
  "+238",
  "+239",
  "+240",
  "+241",
  "+242",
  "+243",
  "+244",
  "+245",
  "+246",
  "+247",
  "+248",
  "+249",
  "+250",
  "+251",
  "+252",
  "+253",
  "+254",
  "+255",
  "+256",
  "+257",
  "+258",
  "+260",
  "+261",
  "+262",
  "+263",
  "+264",
  "+265",
  "+266",
  "+267",
  "+268",
  "+269",
  "+290",
  "+291",
  "+297",
  "+298",
  "+299",
  "+350",
  "+351",
  "+352",
  "+353",
  "+354",
  "+355",
  "+356",
  "+357",
  "+358",
  "+359",
  "+370",
  "+371",
  "+372",
  "+373",
  "+374",
  "+375",
  "+376",
  "+377",
  "+378",
  "+379",
  "+380",
  "+381",
  "+382",
  "+383",
  "+385",
  "+386",
  "+387",
  "+388",
  "+389",
  "+420",
  "+421",
  "+423",
  "+500",
  "+501",
  "+502",
  "+503",
  "+504",
  "+505",
  "+506",
  "+507",
  "+508",
  "+509",
  "+590",
  "+591",
  "+592",
  "+593",
  "+594",
  "+595",
  "+596",
  "+597",
  "+598",
  "+599",
  "+670",
  "+672",
  "+673",
  "+674",
  "+675",
  "+676",
  "+677",
  "+678",
  "+679",
  "+680",
  "+681",
  "+682",
  "+683",
  "+684",
  "+685",
  "+686",
  "+687",
  "+688",
  "+689",
  "+690",
  "+691",
  "+692",
  "+800",
  "+808",
  "+850",
  "+852",
  "+853",
  "+855",
  "+856",
  "+870",
  "+878",
  "+880",
  "+881",
  "+882",
  "+883",
  "+886",
  "+888",
  "+960",
  "+961",
  "+962",
  "+963",
  "+964",
  "+965",
  "+966",
  "+967",
  "+968",
  "+970",
  "+971",
  "+972",
  "+973",
  "+974",
  "+975",
  "+976",
  "+977",
  "+979",
  "+992",
  "+993",
  "+994",
  "+995",
  "+996",
  "+998",
];
export const countriesWithIsoCode = [
  { name: "Afghanistan", code: "AF" },
  { name: "Åland Islands", code: "AX" },
  { name: "Albania", code: "AL" },
  { name: "Algeria", code: "DZ" },
  { name: "American Samoa", code: "AS" },
  { name: "AndorrA", code: "AD" },
  { name: "Angola", code: "AO" },
  { name: "Anguilla", code: "AI" },
  { name: "Antarctica", code: "AQ" },
  { name: "Antigua and Barbuda", code: "AG" },
  { name: "Argentina", code: "AR" },
  { name: "Armenia", code: "AM" },
  { name: "Aruba", code: "AW" },
  { name: "Australia", code: "AU" },
  { name: "Austria", code: "AT" },
  { name: "Azerbaijan", code: "AZ" },
  { name: "Bahamas", code: "BS" },
  { name: "Bahrain", code: "BH" },
  { name: "Bangladesh", code: "BD" },
  { name: "Barbados", code: "BB" },
  { name: "Belarus", code: "BY" },
  { name: "Belgium", code: "BE" },
  { name: "Belize", code: "BZ" },
  { name: "Benin", code: "BJ" },
  { name: "Bermuda", code: "BM" },
  { name: "Bhutan", code: "BT" },
  { name: "Bolivia", code: "BO" },
  { name: "Bosnia and Herzegovina", code: "BA" },
  { name: "Botswana", code: "BW" },
  { name: "Bouvet Island", code: "BV" },
  { name: "Brazil", code: "BR" },
  { name: "British Indian Ocean Territory", code: "IO" },
  { name: "Brunei Darussalam", code: "BN" },
  { name: "Bulgaria", code: "BG" },
  { name: "Burkina Faso", code: "BF" },
  { name: "Burundi", code: "BI" },
  { name: "Cambodia", code: "KH" },
  { name: "Cameroon", code: "CM" },
  { name: "Canada", code: "CA" },
  { name: "Cape Verde", code: "CV" },
  { name: "Cayman Islands", code: "KY" },
  { name: "Central African Republic", code: "CF" },
  { name: "Chad", code: "TD" },
  { name: "Chile", code: "CL" },
  { name: "China", code: "CN" },
  { name: "Christmas Island", code: "CX" },
  { name: "Cocos (Keeling) Islands", code: "CC" },
  { name: "Colombia", code: "CO" },
  { name: "Comoros", code: "KM" },
  { name: "Congo", code: "CG" },
  { name: "Congo, The Democratic Republic of the", code: "CD" },
  { name: "Cook Islands", code: "CK" },
  { name: "Costa Rica", code: "CR" },
  { name: "Cote D'Ivoire", code: "CI" },
  { name: "Croatia", code: "HR" },
  { name: "Cuba", code: "CU" },
  { name: "Cyprus", code: "CY" },
  { name: "Czech Republic", code: "CZ" },
  { name: "Denmark", code: "DK" },
  { name: "Djibouti", code: "DJ" },
  { name: "Dominica", code: "DM" },
  { name: "Dominican Republic", code: "DO" },
  { name: "Ecuador", code: "EC" },
  { name: "Egypt", code: "EG" },
  { name: "El Salvador", code: "SV" },
  { name: "Equatorial Guinea", code: "GQ" },
  { name: "Eritrea", code: "ER" },
  { name: "Estonia", code: "EE" },
  { name: "Ethiopia", code: "ET" },
  { name: "Falkland Islands (Malvinas)", code: "FK" },
  { name: "Faroe Islands", code: "FO" },
  { name: "Fiji", code: "FJ" },
  { name: "Finland", code: "FI" },
  { name: "France", code: "FR" },
  { name: "French Guiana", code: "GF" },
  { name: "French Polynesia", code: "PF" },
  { name: "French Southern Territories", code: "TF" },
  { name: "Gabon", code: "GA" },
  { name: "Gambia", code: "GM" },
  { name: "Georgia", code: "GE" },
  { name: "Germany", code: "DE" },
  { name: "Ghana", code: "GH" },
  { name: "Gibraltar", code: "GI" },
  { name: "Greece", code: "GR" },
  { name: "Greenland", code: "GL" },
  { name: "Grenada", code: "GD" },
  { name: "Guadeloupe", code: "GP" },
  { name: "Guam", code: "GU" },
  { name: "Guatemala", code: "GT" },
  { name: "Guernsey", code: "GG" },
  { name: "Guinea", code: "GN" },
  { name: "Guinea-Bissau", code: "GW" },
  { name: "Guyana", code: "GY" },
  { name: "Haiti", code: "HT" },
  { name: "Heard Island and Mcdonald Islands", code: "HM" },
  { name: "Holy See (Vatican City State)", code: "VA" },
  { name: "Honduras", code: "HN" },
  { name: "Hong Kong", code: "HK" },
  { name: "Hungary", code: "HU" },
  { name: "Iceland", code: "IS" },
  { name: "India", code: "IN" },
  { name: "Indonesia", code: "ID" },
  { name: "Iran, Islamic Republic Of", code: "IR" },
  { name: "Iraq", code: "IQ" },
  { name: "Ireland", code: "IE" },
  { name: "Isle of Man", code: "IM" },
  { name: "Israel", code: "IL" },
  { name: "Italy", code: "IT" },
  { name: "Jamaica", code: "JM" },
  { name: "Japan", code: "JP" },
  { name: "Jersey", code: "JE" },
  { name: "Jordan", code: "JO" },
  { name: "Kazakhstan", code: "KZ" },
  { name: "Kenya", code: "KE" },
  { name: "Kiribati", code: "KI" },
  { name: "Korea, Democratic People'S Republic of", code: "KP" },
  { name: "Korea, Republic of", code: "KR" },
  { name: "Kuwait", code: "KW" },
  { name: "Kyrgyzstan", code: "KG" },
  { name: "Lao People'S Democratic Republic", code: "LA" },
  { name: "Latvia", code: "LV" },
  { name: "Lebanon", code: "LB" },
  { name: "Lesotho", code: "LS" },
  { name: "Liberia", code: "LR" },
  { name: "Libyan Arab Jamahiriya", code: "LY" },
  { name: "Liechtenstein", code: "LI" },
  { name: "Lithuania", code: "LT" },
  { name: "Luxembourg", code: "LU" },
  { name: "Macao", code: "MO" },
  { name: "Macedonia, The Former Yugoslav Republic of", code: "MK" },
  { name: "Madagascar", code: "MG" },
  { name: "Malawi", code: "MW" },
  { name: "Malaysia", code: "MY" },
  { name: "Maldives", code: "MV" },
  { name: "Mali", code: "ML" },
  { name: "Malta", code: "MT" },
  { name: "Marshall Islands", code: "MH" },
  { name: "Martinique", code: "MQ" },
  { name: "Mauritania", code: "MR" },
  { name: "Mauritius", code: "MU" },
  { name: "Mayotte", code: "YT" },
  { name: "Mexico", code: "MX" },
  { name: "Micronesia, Federated States of", code: "FM" },
  { name: "Moldova, Republic of", code: "MD" },
  { name: "Monaco", code: "MC" },
  { name: "Mongolia", code: "MN" },
  { name: "Montserrat", code: "MS" },
  { name: "Morocco", code: "MA" },
  { name: "Mozambique", code: "MZ" },
  { name: "Myanmar", code: "MM" },
  { name: "Namibia", code: "NA" },
  { name: "Nauru", code: "NR" },
  { name: "Nepal", code: "NP" },
  { name: "Netherlands", code: "NL" },
  { name: "Netherlands Antilles", code: "AN" },
  { name: "New Caledonia", code: "NC" },
  { name: "New Zealand", code: "NZ" },
  { name: "Nicaragua", code: "NI" },
  { name: "Niger", code: "NE" },
  { name: "Nigeria", code: "NG" },
  { name: "Niue", code: "NU" },
  { name: "Norfolk Island", code: "NF" },
  { name: "Northern Mariana Islands", code: "MP" },
  { name: "Norway", code: "NO" },
  { name: "Oman", code: "OM" },
  { name: "Pakistan", code: "PK" },
  { name: "Palau", code: "PW" },
  { name: "Palestinian Territory, Occupied", code: "PS" },
  { name: "Panama", code: "PA" },
  { name: "Papua New Guinea", code: "PG" },
  { name: "Paraguay", code: "PY" },
  { name: "Peru", code: "PE" },
  { name: "Philippines", code: "PH" },
  { name: "Pitcairn", code: "PN" },
  { name: "Poland", code: "PL" },
  { name: "Portugal", code: "PT" },
  { name: "Puerto Rico", code: "PR" },
  { name: "Qatar", code: "QA" },
  { name: "Reunion", code: "RE" },
  { name: "Romania", code: "RO" },
  { name: "Russian Federation", code: "RU" },
  { name: "RWANDA", code: "RW" },
  { name: "Saint Helena", code: "SH" },
  { name: "Saint Kitts and Nevis", code: "KN" },
  { name: "Saint Lucia", code: "LC" },
  { name: "Saint Pierre and Miquelon", code: "PM" },
  { name: "Saint Vincent and the Grenadines", code: "VC" },
  { name: "Samoa", code: "WS" },
  { name: "San Marino", code: "SM" },
  { name: "Sao Tome and Principe", code: "ST" },
  { name: "Saudi Arabia", code: "SA" },
  { name: "Senegal", code: "SN" },
  { name: "Serbia and Montenegro", code: "CS" },
  { name: "Seychelles", code: "SC" },
  { name: "Sierra Leone", code: "SL" },
  { name: "Singapore", code: "SG" },
  { name: "Slovakia", code: "SK" },
  { name: "Slovenia", code: "SI" },
  { name: "Solomon Islands", code: "SB" },
  { name: "Somalia", code: "SO" },
  { name: "South Africa", code: "ZA" },
  { name: "South Georgia and the South Sandwich Islands", code: "GS" },
  { name: "Spain", code: "ES" },
  { name: "Sri Lanka", code: "LK" },
  { name: "Sudan", code: "SD" },
  { name: "Suriname", code: "SR" },
  { name: "Svalbard and Jan Mayen", code: "SJ" },
  { name: "Swaziland", code: "SZ" },
  { name: "Sweden", code: "SE" },
  { name: "Switzerland", code: "CH" },
  { name: "Syrian Arab Republic", code: "SY" },
  { name: "Taiwan, Province of China", code: "TW" },
  { name: "Tajikistan", code: "TJ" },
  { name: "Tanzania, United Republic of", code: "TZ" },
  { name: "Thailand", code: "TH" },
  { name: "Timor-Leste", code: "TL" },
  { name: "Togo", code: "TG" },
  { name: "Tokelau", code: "TK" },
  { name: "Tonga", code: "TO" },
  { name: "Trinidad and Tobago", code: "TT" },
  { name: "Tunisia", code: "TN" },
  { name: "Turkey", code: "TR" },
  { name: "Turkmenistan", code: "TM" },
  { name: "Turks and Caicos Islands", code: "TC" },
  { name: "Tuvalu", code: "TV" },
  { name: "Uganda", code: "UG" },
  { name: "Ukraine", code: "UA" },
  { name: "United Arab Emirates", code: "AE" },
  { name: "United Kingdom", code: "GB" },
  { name: "United States", code: "US" },
  { name: "United States Minor Outlying Islands", code: "UM" },
  { name: "Uruguay", code: "UY" },
  { name: "Uzbekistan", code: "UZ" },
  { name: "Vanuatu", code: "VU" },
  { name: "Venezuela", code: "VE" },
  { name: "Viet Nam", code: "VN" },
  { name: "Virgin Islands, British", code: "VG" },
  { name: "Virgin Islands, U.S.", code: "VI" },
  { name: "Wallis and Futuna", code: "WF" },
  { name: "Western Sahara", code: "EH" },
  { name: "Yemen", code: "YE" },
  { name: "Zambia", code: "ZM" },
  { name: "Zimbabwe", code: "ZW" },
];
export const schools = [
  "A.P.S, Sargodha",
  "Abaidullah College - Bahawalnagar",
  "Abaidullah Educational Complex Pakpattan, Lahore",
  "Abbottabad Memon Academy - Abbottabad",
  "Abbottabad Private Intermediate",
  "Abdul Razaq Fazaia College, MM Allam Base, Mianwali, Mianwali",
  "Abdullah Govt. College for Women, Karachi",
  "ABICS (Sargodha)",
  "Academy (Lahore)",
  "Adamjee Govt. Science College, Baden",
  "Adamjee Govt. Science College, Bahawalpur",
  "Adamjee Govt. Science College, Chaman",
  "Adamjee Govt. Science College, Dadu",
  "Adamjee Govt. Science College, Dargai",
  "Adamjee Govt. Science College, Haveli Lakha",
  "Adamjee Govt. Science College, Hyderabad",
  "Adamjee Govt. Science College, Islamkot",
  "Adamjee Govt. Science College, Kandiaro",
  "Adamjee Govt. Science College, Karachi",
  "Adamjee Govt. Science College, Kashmor",
  "Adamjee Govt. Science College, Khairpur",
  "Adamjee Govt. Science College,  Quetta",
  "Adamjee Govt. Science College, Rawalpindi",
  "Adamjee Govt. Science College, Thatta",
  "Adamjee Govt. Science College,Peshawar",
  "Admire College of Science and Commerce, Multan",
  "Afaq College Vehari",
  "Afridi Model School and College, Peshawar",
  "Aga Khan Higher Secondary School Hunza",
  "Aga Khan Higher Secondary School, Chitral",
  "Aga Khan Higher Secondary School, Gilgit",
  "Aga Khan Higher Secondary School, Islamabad",
  "Aga Khan Higher Secondary School, Karachi",
  "Aga Khan School Murtazabad Hunza, Islamabad",
  "Air Base Inter College, Sargodha",
  "Aisha Bawany Academy, Karachi",
  "Aitchison Model School, Lahore",
  "Al Badr Public High School, Karachi",
  "Al Huda School and College, Wah Cantt",
  "Al-Ain Juniors,Lahore",
  "Alfalah Group of Colleges, Faisalabad",
  "Ali Trust College, Islamabad",
  "Alizium College, Lodhran",
  "Allama Iqbal Govt. Girls College, Karachi",
  "Allied School, Bhakkar",
  "Allied School, Charsadda",
  "Allied School, Gujranwala",
  "Allied School, Karachi",
  "Allied School, Kasur",
  "Allied School, Khairpur",
  "Allied School, Lahore",
  "Allied School, Quetta",
  "Allied School, Rawalpindi",
  "Allied School, Swat",
  "Almadina, Saidu Sharif",
  "Alpha College, Karachi",
  "Alpha College, Lahore",
  "Alpine College Khanpur, Bahawalpur",
  "Alpine College, Rahim Yar Khan",
  "Anees Hussain, Karachi",
  "Anees Hussain, Mirpur Khas",
  "Anees Hussain, Nawabshah",
  "Anees Hussain, Quetta",
  "APC, Lahore",
  "Apex Group of Colleges, Gujranwala",
  "APS Humyun Road, Rawalpindi",
  "APS Pasban Rawalpindi, Attock",
  "APS Seven Streams Quetta Cantt, Quetta",
  "APS, Fort Iqbal DI Khan",
  "APS, Islamabad",
  "APS, Kasur",
  "APS, Mardan",
  "APS, Mirpur",
  "APS, Multan",
  "APS, Peshawar",
  "APS, Rawalpindi",
  "APS, Sargodha",
  "APSACS Tarbela Cantt, Islamabad",
  "APSACS, Bahawalpur",
  "APSACS, Islamabad",
  "APSACS, Lahore",
  "APSACS, Rawalpindi",
  "AQK, Islamabad",
  "Army Burn Hall College for Girls ATD, Abbottabad",
  "Army Public Degree College,Karachi",
  "Army Public School and College Attock, Attock",
  "Army Public School and College Pasban, Rawalpindi",
  "Army Public School, Abbottabad",
  "Army Public School, Attock",
  "Army Public School, Bagh",
  "Army Public School, Bahawalnagar",
  "Army Public School, Bahawalpur",
  "Army Public School, Gujranwala",
  "Army Public School, Hyderabad",
  "Army Public School, Islamabad",
  "Army Public School, Jhelum",
  "Army Public School, Karachi",
  "Army Public School, Kharian",
  "Army Public School, Mardan",
  "Army Public School, Peshawar",
  "Army Public School, Rawalpindi",
  "Army Public School, Sialkot",
  "Army Public School, Sukkur",
  "Askari Degree College, Karachi",
  "Askari Intermediate College, Karachi",
  "Askaria College, Rawalpindi",
  "Aspire College, Vehari",
  "Aspire College, Faisalabad",
  "Aspire College, Gujranwala",
  "Aspire College, Islamabad",
  "Aspire College, Jhang",
  "Aspire College, Lahore",
  "Aspire College, Mirpur",
  "Aspire College, Multan",
  "Aspire College, Sialkot",
  "Aspire College, Toba Tek Singh",
  "Aspire Group of College, Lahore",
  "Aspire Group of Colleges, Jhelum",
  "Aspire Group of Colleges, Mirpur",
  "Astron College of Science and Commerce, Islamabad",
  "Attock F.G. Post Graduate College for Women, Wah Cantt.",
  "Attock Fazaia Degree College ARF PAC Kamra",
  "Attock Lahore Grammar School",
  "Awaran Degree College, Quetta",
  "Azam Gar, Abbottabad",
  "Aziz Bhatti Shaheed Army College, Mardan",
  "BAAM PECHS Govt. College for Women - Karachi",
  "Bahawalpur Govt. Girls Degree College, Nazimabad, Karachi",
  "Bahawalpur Punjab Group of Colleges",
  "Bahria College, Baden",
  "Bahria College, Islamabad",
  "Bahria College, Karachi",
  "Bahria College, Lahore",
  "Bahria College, Turbat",
  "Bahria Foundation College, Karachi",
  "Balochistan Residential College, Loralai, Dera Ghazi Khan",
  "BAMM PECHS Govt. College for Women, Karachi",
  "Bannu Model School and College, Bannu",
  "Barret Hodgson, Toba Tek Singh",
  "Beacon Light Academy, Karachi",
  "Beaconhouse College - Karachi",
  "Beaconhouse College Programme, Peshawar",
  "Beaconhouse School, Abbottabad",
  "Beaconhouse School, Daska",
  "Beaconhouse School, Dina City|Dina",
  "Beaconhouse School, Faisalabad",
  "Beaconhouse School, Gujranwala",
  "Beaconhouse School, Hyderabad",
  "Beaconhouse School, Islamabad",
  "Beaconhouse School, Karachi",
  "Beaconhouse School, Kohat",
  "Beaconhouse School, Kotri",
  "Beaconhouse School, Lahore",
  "Beaconhouse School, Multan",
  "Beaconhouse School, Quetta",
  "Beaconhouse School, Sukkur",
  "Behbud Association, Karachi",
  "Benchmark, Rawalpindi",
  "Bhakkar Punjab Group of Colleges",
  "Bhimber Read Foundation College, Bhimber",
  "Bibi Asifa Govt. Girls College, Karachi",
  "BNB Girls College, Larkana",
  "Bolan Medical College, Quetta",
  "Boys Degree College, Larkana",
  "Bright Vision, Haripur",
  "Brite Vision Model School and College",
  "BTSC, Lahore",
  "C&S Degree College, Shikarpur",
  "Cadet College Ghokti, Kashmor",
  "Cadet College Kallar Kahar, Peshawar",
  "Cadet College Killa Saifullah, Pishin",
  "Cadet College Killa Saifullah, Quetta",
  "Cadet College Pano Aqil, Sukkur",
  "Cadet College Sanghar, Tando Adam",
  "Cadet College Wana, Dera Ismail Khan",
  "Cadet College, Hassanabdal",
  "Captain Hussain Khan Shaheed College, Rawalakot",
  "Cedar College, Karachi",
  "Chakwal Chenab College Jhang",
  "Chakwal Punjab Group of Colleges",
  "Chand Bagh, Quetta",
  "Chenab College, Jhang",
  "Chichawatni Private Intermediate - Chichawatni",
  "Chichawatni, Reader Group of College",
  "Chiniot Chenab College Jhang",
  "Chiniot Islamia College, Karachi",
  "City Public College - Karachi",
  "The City School",
  "College for Girl New Lalazar Rawalpindi, Rawalpindi",
  "College of Emerging Technologies, Karachi",
  "College of Excellence, Hyderabad",
  "COMMECS College, Karachi",
  "Concept, Thatta",
  "Concepts Collage of Sciences, Rawalpindi",
  "Concordia College, Islamabad",
  "Concordia College, Kasur",
  "Concordia, Nowshera",
  "Cordoba School for A-Levels, Karachi",
  "County Girls College, Hyderabad",
  "CPHSS, Rohri",
  "Credo College - Karachi",
  "D.J Sindh Govt. Science College, Hyderabad",
  "D.J Sindh Govt. Science College, Karachi",
  "DA Public School, Islamabad",
  "Daanish Boys School RYK, Rahim Yar Khan",
  "Danish Public Schools, Chakdara",
  "Dar-e-Arqam School and College, Dera Ismail Khan",
  "Dar-e-Arqam Schools, Gujrat",
  "Dar-e-Arqam Schools, Sargodha",
  "DAV Public Higher Secondary School, Ghotki",
  "Dawn College, Swat",
  "Dawood Public School A-Levels, Karachi",
  "Degree College Dera Nawab Sahab, Bahawalnagar",
  "Degree College for Women Nazimabad, Karachi",
  "Degree College Nawabshah, Nawabshah",
  "Degree College Qasimabad, Hyderabad",
  "Degree College Thul, Karachi",
  "Degree College Zehri, Khuzdar",
  "Degree College, Hab Chauki",
  "Degree College, Kandkot",
  "Degree College, Larkana",
  "Degree College, Nawabshah",
  "Degree College, Nushki",
  "Degree College, Peshawar",
  "Dera Bugti Govt. Degree Boys College, Karachi",
  "DHA College, Karachi",
  "DHACSS College for Women, Karachi",
  "DHACSS Degree College, Karachi",
  "Divisional Public School and College, Faisalabad",
  "Divisional Public School and College, Sahiwal",
  "DJ Model High School Oshikhandass Gilgit, Islamabad",
  "DJPS College, Mandi Bahauddin",
  "Doaba Public School and College Doaba (Hangu)",
  "DPS, Lahore",
  "DPS, Okara",
  "DPS, Sahiwal",
  "Dr A.Q. Khan School and College, Islamabad",
  "Dubai International Mansehra, Abbottabad",
  "Dubai International School",
  "E.A.B Haroon Bahria, Karachi",
  "Eden College, Karachi",
  "Educator College, Chichawatni",
  "Edward College Peshawar, Nowshera",
  "Edwards College Peshawar",
  "Emalah Foundation, Rawalpindi",
  "Emallah Foundation, Rawalpindi",
  "Excellence School and College Panoaqil, Sukkur",
  "F.G Degree College, Bannu District|Bannu",
  "F.G Postgraduate College Kashmir Road Rawal (Rawalpindi)",
  "F.G Sir Syed College The Mall, Rawalpindi",
  "F.G, Rawalpindi",
  "Faisalabad Allied School",
  "Faisalabad DMC",
  "Faisalabad Government College, Faisalabad",
  "Faisalabad Punjab Group of Colleges",
  "Falconhouse Grammar School, Baden",
  "Faran College, Pirmahal",
  "Faran Model College for Women, Jhang",
  "Fateh Jang, Govt. Degree Boys College, Karachi",
  "Fatima Jinnah College, Karachi",
  "Fatima Public School and College, Islamabad",
  "Fatimiyah Girls College, Karachi",
  "Fauji Foundation College - Fateh Jang",
  "Fauji Foundation College - Islamabad",
  "Fauji Foundation College for Girls, Rawalpindi",
  "Fauji Foundation College, Gujar Khan",
  "Fauji Foundation College, Larkana",
  "Fauji Foundation, Nowshera",
  "Fazaia Degree College ARF Kamra, Attock",
  "Fazaia Degree Collegel Karachi",
  "Fazaia Degree College, Kalam",
  "Fazaia Degree College, Peshawar",
  "Fazaia Inter College",
  "Fazaia Inter College Kohat, Kohat",
  "Fazaia Inter College Minhas, Haripur",
  "Fazaia Inter College, Attock",
  "Fazaia Inter College, Islamabad",
  "Fazaia Inter College, Lahore",
  "Fazaia Inter College, Mianwali",
  "Fazaia Inter College, Rawalpindi",
  "FCA, Swat",
  "FDC ARF Kamra, Attock",
  "Federal College of Sciences and Commerce",
  "FFC Grammar School and College Mirpur Mathelo",
  "FFCG New Lalazar, Rawalpindi",
  "FG College Mangla - Lahore",
  "FG College Mangla Cantt, Dina City|Dina",
  "FG College, Haripur",
  "FG College, Hyderabad",
  "FG Degree College, Rawalpindi",
  "FG Girls Inter College, Karachi",
  "FG Postgraduate College for Women RWP (Rawalpindi)",
  "FG Postgraduate College for Women, Wah Cantt",
  "FG Sir Syed College, Islamabad",
  "FG, Attock",
  "Forward Girls College, Peshawar",
  "Foundation Public School, Chakwal",
  "Foundation Public School, Hyderabad",
  "Foundation Public School, Karachi",
  "Froebel Education Centre, Islamabad",
  "Frontier College for Women (Peshawar)",
  "Fusion College Shakargarh, Shakargarh",
  "Garission Science college barnala (Bhimber)",
  "Garrison Academy, Islamabad",
  "Garrison Academy, Kharian",
  "Garrison Academy, Quetta",
  "Garrison Cadet College Kohat",
  "Garrison Degree College, Quetta",
  "GCS, Rawalpindi",
  "GCU Lahore, Lahore",
  "Generation's School, Karachi",
  "Ghazali School and College Elai (Buner)",
  "Ghousia Institute of Fast and Technology (Kotli)",
  "Girls College, Dadu",
  "Girls Govt College - Karachi",
  "Girls High School (Hyderabad)",
  "Global College, Rawalpindi",
  "Global Degree College - Peshawar",
  "GMC, Mirpur",
  "Gov Girls Degree Clg, Karachi",
  "Gov High Girls School, Sukkur",
  "Government (Mirpur Khas)",
  "Government Boys College Kashmore, Kashmor",
  "Government Boys Degree College (Larkana)",
  "Government Boys Degree College Asifabad, Karachi - Buner",
  "Government Boys Degree College Jacobabad - Jacobabad",
  "Government Boys Degree College Umerkot (Umarkot)",
  "Government College Jhang (Jhang)",
  "Government College Peshawar",
  "Government College Peshawar, Other",
  "Government College Peshawar, Peshawar",
  "Government Degree Boys and Girls College, Karachi",
  "Government Degree Boys College 11 A North Karachi, Karachi",
  "Government Degree College (Bahawalpur)",
  "Government Degree College Diplo, Hyderabad",
  "Government Degree College KN Shah, Mehar",
  "Government Degree College Mingora Swat",
  "Government Degree College Muzaffargarh, Muzaffar Garh",
  "Government Degree College, Hyderabad",
  "Government Degree Malir Cantt, Karachi, Karachi",
  "Government Girls College (Hyderabad)",
  "Government Girls College F-10 (Islamabad)",
  "Government Girls College, Mirpur",
  "Government Girls Degree College, Larkana",
  "Government Girls Higher Secondary School Khairpur, Khairpur",
  "Government Girls Higher Secondary School, Sukkur",
  "Government High School - Kandiaro, Karachi",
  "Government Higher Secondary School, Mehmodkot, Multan",
  "Government Inter College, Mashkay, Quetta",
  "Government Jahanzeb College Swat, Swat",
  "Government Model High School Renala Khurd (Renala Khurd)",
  "Government, Digri",
  "Govt B Higher Secondary School, Nawabshah",
  "Govt Boys College Uthal, Uthal",
  "Govt Boys Degree College (Naushara)",
  "Govt Boys Degree College Daulatpur (Nawabshah)",
  "Govt Boys Degree College Larkana, Larkana",
  "Govt Boys Degree College Mithi, Mithi",
  "Govt Clg Samundru (Abbottabad)",
  "Govt College Bhakkar, Bhakkar",
  "Govt College Ghorabari, Thatta",
  "Govt College Kamalia (Kamalia)",
  "Govt College Peshawar, Mardan",
  "Govt College, Lahore",
  "Govt Degree College Dadu, Dadu",
  "Govt Degree College Daharki - Ghotki",
  "Govt Degree College for Women, Lahore",
  "Govt Degree College Hyderabad, Hyderabad",
  "Govt Degree College Larkana, Larkana",
  "Govt Degree College Mingora, Swat",
  "Govt Degree College Sehwan Sharif - Hyderabad",
  "Govt degree college Turbat (Quetta)",
  "Govt Degree College Usta Muhammad (Quetta)",
  "Govt Degree College, Karachi",
  "Govt Degree College, Lahore",
  "Govt Degree College, Malir Cantt, Karachi",
  "Govt Frontier College, Peshawar",
  "Govt Girls College, Karachi, Karachi",
  "Govt Girls Degree College - Larkana",
  "Govt Girls Degree College Sanghar, Shingar",
  "Govt Girls Degree College Sheikh Zaid Islamic Cent (Karachi)",
  "Govt Girls Degree College, Lakki Marwat",
  "Govt Girls Higher Secondary School (Bahawalpur)",
  "Govt Girls Higher Secondary School, ARF PAC Kamra, Attock",
  "Govt Girls Higher Secondary School, Sukkur",
  "Govt Girls Post Graduate College Quetta, Quetta",
  "Govt Girls Shah Latif College - Hyderabad",
  "Govt Graduate College for Women Model Town (Dera Ghazi Khan)",
  "Govt Graduate College Lahore, Lahore",
  "Govt High Secondary School Dir Lower, Peshawar",
  "Govt Mehran Degree College Moro, Nawabshah",
  "Govt Post Graduate College - Toba Tek Singh, Toba Tek Singh",
  "Govt Post Graduate Jahanzaib College Swat, Shangla",
  "Govt Science College Quetta, Quetta",
  "Govt. Aisha Bawani College - Karachi, Karachi",
  "Govt. Associate College for Girls, Muzaffargarh, Muzaffar Garh",
  "Govt. Associate College for Women - Kot Chutta, Dera Ghazi Khan",
  "Govt. Associate College Jalal Pur Bhattian, Hafizabad",
  "Govt. Boys Comprehensive H.S.S., Azizabad, Karachi",
  "Govt. Boys Degree College Matli, Baden",
  "Govt. Boys H.S.S Jacobabad",
  "Govt. City College Musa Colony, Abbottabad",
  "Govt. City College Musa Colony, Karachi (Attock)",
  "Govt. College for Men, Nazimabad, Karachi",
  "Govt. College for Women, Korangi 06, Karachi (Karachi)",
  "Govt. College for Women, Nazimabad, Karachi",
  "Govt. College for Women, Shahrah-e-Liaquat, Karachi",
  "Govt. College for Women, Shahrah-e-Liaquat, Karachi, Nawabshah",
  "Govt. College Peshawar",
  "Govt. College Taunsa (Dera Ghazi Khan)",
  "Govt. College University, Lahore",
  "Govt. College, Chakwal",
  "Govt. Comprehensive H.S.S, Korangi-0.3, Karachi, Karachi",
  "Govt. Comprehensive H.S.S, North Nazimabad, Karachi, Karachi",
  "Govt. Degree Boys College - Gulzar-e-Hijri, Karachi",
  "Govt. Degree Boys College, Gulistan-e-Jauhar, Hyderabad",
  "Govt. Degree Boys College, Gulistan-e-Jauhar, Karachi",
  "Govt. Degree Boys College, Gulistan-e-Jauhar, Shikarpur",
  "Govt. Degree Boys College, Gulzar-e-Hijri, Karachi",
  "Govt. Degree Boys College, Gulzar-e-Hijri, Karachi, Karachi",
  "Govt. Degree College - Larkana",
  "Govt. Degree College - Sukkur",
  "Govt. Degree College DB, Dera Bugti",
  "Govt. Degree College for Boys and Girls Stadium Road, Karachi",
  "Govt. Degree College for Women, Nazimabad, Karachi, Karachi",
  "Govt. Degree College JCD, Jacobabad",
  "Govt. Degree College Malir Cantt, Karachi, Karachi",
  "Govt. Degree College Mehar",
  "Govt. Degree College Pasni - Pasni City",
  "Govt. Degree College Shahdatkot (Larkana)",
  "Govt. Degree College Swat, Swat",
  "Govt. Degree College Thari Mirwah, Karachi",
  "Govt. Degree College Therhi, Khairpur",
  "Govt. Degree College Zamzama, Karachi",
  "Govt. Degree College, Dera Ghazi Khan",
  "Govt. Degree College, Malir Cantt, Karachi",
  "Govt. Degree College, Mingora, Swat - Mingora, Swat",
  "Govt. Degree College, SRE Majeed, Karachi, Karachi",
  "Govt. Degree College, Swat",
  "Govt. Degree Girls College JCD, Karachi",
  "Govt. Degree Girls College Matli (Other)",
  "Govt. Degree Girls College, Al-Noor, FB Area, Karachi, Khairpur",
  "Govt. Degree Girls College, Baldia Town, Karachi",
  "Govt. Degree Girls College, Bufferzone, Karachi",
  "Govt. Degree Girls College, Ibrahim Hydri, Karachi, Attock",
  "Govt. Degree Girls College, Nawabshah, Nawabshah",
  "Govt. Degree Girls College, Noshki, Balochistan - Noshki",
  "Govt. Degree Girls College, Orangi, Karachi, Hyderabad",
  "Govt. Degree Girls College, Surjani Town, Peshawar",
  "Govt. Degree High School Attock, Attock",
  "Govt. Degree Science & Commerce College, Gulshan-e-Iqbal, Karachi",
  "Govt. Delhi Inter Science College (Karachi)",
  "Govt. Girls College, PIB Colony, Karachi, Gujranwala",
  "Govt. Girls Degree College",
  "Govt. Girls Degree College Booni, Chitral",
  "Govt. Girls Degree College, Nawabshah, Nawabshah",
  "Govt. Girls H.S.S. Bhiro Village, Karachi, Karachi",
  "Govt. Girls High School KGM District Mirpurkhas, Jamesabad",
  "Govt. Girls High School, Khairpur",
  "Govt. Girls Higher Secondary School - Mehar",
  "Govt. Girls Higher Secondary School Jamshoro (Jamshoro)",
  "Govt. Girls Higher Secondary School, Mana Ahmadani, Dera Ghazi Khan",
  "Govt. Girls Science College, Shah Faisal Colony - Karachi",
  "Govt. Graduate College, Bhakkar",
  "Govt. High School Bugti Colony Sui",
  "Govt. Islamia College Sarghoda Road Faisalabad, Faisalabad",
  "Govt. Islamia Science College Sukkur (Sukkur)",
  "Govt. Jamia Millia Degree College, Karachi, Karachi",
  "Govt. Mumtaz Boys H.S.S. Landhi, Karachi, Dera Bugti",
  "Govt. Municipal Graduate College (Faisalabad)",
  "Govt. National College, Hyderabad",
  "Govt. National College, Karachi",
  "Govt. National College, Karachi, Peshawar",
  "Govt. Nazareth Degree Girls College, Hyderabad",
  "Govt. PECHS Education Foundation Science College, Karachi",
  "Govt. PECHS Education Foundation Science College, Karachi, Larkana",
  "Govt. PECHS Education Foundation Science College, Karachi, Sargodha",
  "Govt. PECHS Education Foundation Science College, Karachi, Sukkur",
  "Govt. PECHS Education Foundation Science School, Lahore",
  "Govt. Post Graduate College Mardan, Mardan",
  "Govt. Post, Bahawalnagar",
  "Govt. Postgraduate Science College, Quetta",
  "Govt. SAL College Mirpurkhas - Mirpurkhas",
  "Govt. Science College, Quetta",
  "Govt. Shadani Degree College",
  "Govt. SMB Fatima Jinnah Girls College, Karachi",
  "Govt. Superior Science College, Karachi",
  "Govt. Superior Science College, Karachi, Jacobabad",
  "Govt. Superior Science College, Karachi, Karachi",
  "Govt. Superior Science College, Karachi, Larkana",
  "Govt. Superior Science College, Karachi, Peshawar",
  "Govt. Waliyat Hussain Islamia College Multan (Multan)",
  "Govt.Degree college Mingora Swat (Swat)",
  "GPGC Mandian Abbottabad - Rawalpindi",
  "GPGCW Mardan, Abbottabad",
  "Guardian Colleges, Layyah",
  "Gujranwala APSACS Gujranwala",
  "Gul Model Science College, Jacobabad",
  "Gulistan S.A.L School, Karachi",
  "Habib Girls School, Karachi",
  "Hadaf College Peshawar, Peshawar",
  "Haji Abdullah Haroon Govt. College, Naokot",
  "Hamdard Public School, Mirpur Khas",
  "Hamza APS, Islamabad",
  "Hamza APS, Rawalpindi",
  "Hamza Army Public School And College (Rawalpindi)",
  "Hamza Army Public School Rawalpindi, Rawalpindi",
  "Hamza Army, Islamabad",
  "Happy Home School - Hyderabad",
  "Happy Palace Grammar Schools - Karachi",
  "Haq Bahoo Sultan School, Kashmor",
  "Haripur Bright Vision",
  "Haroon Bahria College, Karachi",
  "Hawajee Girls College - Karachi",
  "Hayat College, Hyderabad",
  "Hayat Girls College, Hyderabad",
  "Hayat Girls Higher Secondary School and College - Hyderabad",
  "Hayat-ul-Islam, Karachi",
  "Highbrow College",
  "Highbrow College, Karachi",
  "HIMS - Peshawar",
  "Hira College - Bahawalnagar",
  "Hira College, Dargai",
  "Hira Foundation, Karachi",
  "HITEC SCFG, Abbottabad",
  "HM Khoja Girls, Nawabshah",
  "Hope Science School and College, Attock",
  "Hyderabad Adamjee Govt. Science College, Karachi",
  "Hyderabad Army Public School",
  "Hyderabad Beaconhouse School",
  "Hyderabad College",
  "Hyderabad Excellence Education System",
  "Hyderabad Foundation Public School",
  "Hyderabad Govt Degree College",
  "Hyderabad Hayat Girls College",
  "Hyderabad Public School, Karachi",
  "Hyderabad The City School",
  "IBA Community College NF, Khairpur",
  "IBA Ghotki, Ghotki",
  "IBA PS Ubauro (Kashmor)",
  "IBA Public School (Sukkur)",
  "IBA, Jacobabad",
  "IBA-Public School Sukkur (Sukkur)",
  "Ibn-e-Rushed College, Hyderabad",
  "Ibn-n-Rushed Girls College, Mirpurkhas",
  "ICG F6 2, Islamabad",
  "ICP, Peshawar",
  "Ideal Allama Iqbal Girls Higher Secondary School G (Faisalabad)",
  "Ilm College, Sargodha",
  "IMCB (Islamabad)",
  "IMCG (Islamabad)",
  "IMCG (Rawalpindi)",
  "IMCG, Islamabad",
  "Improver (Thatta)",
  "Improver (Vehari)",
  "Indus College, Quetta",
  "Inspire (Sargodha)",
  "International Islamia College Buner (Buner)",
  "International School Lahore (Lahore)",
  "International School of Creative Science, Karachi",
  "Iqra Education System School and College Tank, Tank City",
  "Iqra Huffaz Girls College, Karachi",
  "Iqra Public School and College Kohat, Kohat",
  "Iqra Residential School and College, Pishin",
  "Iqra School and College Bannu, Bannu",
  "Iqra, Kohat",
  "Islamabad AKHSS, Gilgit",
  "Islamabad Beaconhouse School",
  "Islamabad Career College - Islamabad",
  "Islamabad College (Islamabad)",
  "Islamabad College for Girls F-6/2, Islamabad",
  "Islamabad College for Girls, Islamabad",
  "Islamabad Hitec",
  "Islamabad Mdct",
  "Islamabad Model College for Girls F-6/2 (Islamabad)",
  "Islamabad Model College for Girls G-10/4, Islamabad",
  "Islamabad Model College for Girls I-10/4 (Islamabad)",
  "Islamabad Public School and College Jutial Gilgit",
  "Islamabad Punjab Group of Colleges",
  "Islamabad Super Nova",
  "Islamabad Westminster School & College",
  "Islamabad White",
  "Islami College - Peshawar",
  "Islamia College",
  "Islamia College Civil Lines Lahore (Lahore)",
  "Islamia College for Girls, Lahore (Copper Road)",
  "Islamia College Peshawar (Peshawar)",
  "Islamia College Peshawar, Peshawar",
  "Islamia Girls College, Quetta",
  "Islamia Govt. Science College (Kalat)",
  "Islamia Govt. Science College - Nawabshah",
  "Islamia Govt. Science College, Abbottabad",
  "Islamia Govt. Science College, Bhimber",
  "Islamia Govt. Science College, Charsadda",
  "Islamia Govt. Science College, Karachi",
  "Islamia Govt. Science College, Karachi, Jamshoro",
  "Islamia Govt. Science College, Karachi, Karachi",
  "Islamia Govt. Science College, Karachi, Naushara",
  "Islamia Govt. Science College, Lakki Marwat",
  "Islamia Govt. Science College, Quetta",
  "Islamia Model College, Chakdara",
  "Islamia Public High School Ghotki, Ghotki",
  "Islamic Science College Shahdadpur - Hab Chauki",
  "Islamiya Girls College, Quetta",
  "Islamkot The City School",
  "Jacobabad Fazaia Inter College",
  "Jahangir Shaheed FC Public School and College (Sargodha)",
  "Jam Mumtaz Hussain Dahar Government Degree College - Ghotki",
  "Jamshoro Government Girls College Jamshoro Colony",
  "Jauharabad District Public School and Inter College, Khushab",
  "Jhang Chenab College Jhang",
  "Jhelum College",
  "Jinnah Basic School and Girls College - Mansehra",
  "Jinnah College for Women, Peshawar",
  "Jinnah College for Women, University of Peshawar - Mardan",
  "Jinnah College Gojra, Faisalabad",
  "Jinnah Jam E, Haripur",
  "Jinnah Public School and College Hafiz Hayat Gujra, Gujrat",
  "Jinnah School and College, Bhakkar",
  "Jinnah Sindh Medical University, Karachi",
  "Jonah College for Women UOP - Peshawar",
  "Kaghan Memorial School Kawai Balakot, Mansehra",
  "Kaizen High, Lahore",
  "Kalar Kahar Science College, Chakwal",
  "Karachi Adamjee Govt. Science College",
  "Karachi D.H.A.C.S.S. College for Women",
  "Karachi D.H.A.C.S.S. Degree College for Women, Phase 8",
  "Karachi D.H.A.C.S.S. Shaikh Khalifa Bin Zayed Campus",
  "Karachi D.J Sindh Govt. Science College",
  "Karachi F.G. Post Graduate College for Women, Wah Cantt.",
  "Karachi Grammar School, Karachi",
  "Karachi Hayat Girls Degree College",
  "Karachi Khatoon-e-Pakistan Government College for Women, Stadium Road",
  "Karachi Memon College",
  "Karachi Meritorious Science College, Karachi",
  "Karachi Nixor A-Levels",
  "Karachi P.E.C.H.S. Govt. College for Women",
  "Karachi Pakistan Shipowner Government College",
  "Karachi Scholars Group of Education",
  "Karachi Science and Commerce Degree College, Gulshan-e-Iqbal",
  "Karachi St. Bonaventure High School",
  "Karachi St. Joseph College for Women",
  "Karachi St. Joseph's College",
  "Karachi St. Lawrance Govt. College for Women",
  "Karachi The City School",
  "Karachi The Lyceum A-Levels",
  "Karachi Usman Public School",
  "Karak City APWA Govt. College for Women, Karachi",
  "Karnak Girls College, Kotli",
  "Kashmir Model College, Mirpur",
  "Kashmore (Kashmor)",
  "Kasur (Kasur)",
  "Kech Grammar High School Turbat, Turbat",
  "Kent College of Science and Commerce (Karachi)",
  "Khai, Khairpur",
  "Khairpur Women College Khairpur",
  "Khaldunia Public School, Islamabad",
  "Khan Academy Peshawar, Batagram",
  "Khatoon-e-Pakistan Government College for Women, Stadium Road, Karachi",
  "Khuiratta Girls College, Kotli",
  "Khurshed Gov Girls Degree College, Karachi",
  "KIAS, Mirpur",
  "Kinnaird College, Lahore",
  "KIPS (Sargodha)",
  "KIPS Academy (Lahore)",
  "KIPS Academy - Gujranwala",
  "KIPS College",
  "KIPS College (Multan)",
  "KIPS College Okara (Okara)",
  "KIPS College, Bahawalpur",
  "KIPS College, Faisalabad",
  "KIPS College, Gujranwala",
  "KIPS College, Islamabad",
  "KIPS College, Lahore",
  "KIPS College, Multan",
  "KIPS College, Wah Cantt",
  "KIPS, Bahawalpur",
  "KIPS, Khanewal",
  "KIPS, Lahore",
  "KIPS, Rawalpindi",
  "KMA girls degree college (Karachi)",
  "KMC (Peshawar)",
  "Lahore Aitchison Model School",
  "Lahore College and University, Lahore",
  "Lahore College for Women University (Lahore)",
  "Lahore College Jail Road - Lahore",
  "Lahore College, Lahore",
  "Lahore Government College University Lahore",
  "Lahore Grammar School",
  "Lahore School System Rawalpindi, Rawalpindi",
  "Larkana - Nasirabad, Larkana",
  "Lawrence College Murre (Quetta)",
  "Learners Academy, Hyderabad",
  "Leeds School and College (Dera Ismail Khan)",
  "LGS (Lahore)",
  "Maahal Degree College, Wah Cantt",
  "Madina College, Faisalabad",
  "Mansehra",
  "Mashal Degree College, Wah Cantt",
  "Mazhar Muslim College Ranipur, Khairpur",
  "Mazhar Muslim Model Higher Secondary School, Ranipur, Ghotki",
  "Mehran Degree College, Dadu",
  "Memon Academy High School, Sakrand",
  "Meritorious Education Centre (Karachi)",
  "Meritorious Science College, Karachi (Karachi)",
  "Metropolis Intermediate College (Karachi)",
  "Military College Muree (Burewala)",
  "Minhas College, Attock",
  "MM Academy, Peshawar",
  "MPHS School, Ranipur",
  "MTB College (Rahim Yar Khan)",
  "Multan Nishat College of Science Lodhi Colony Multan",
  "Multan University",
  "Munir College, Islamabad",
  "Muslim College - Peshawar",
  "Muslim College, Multan",
  "Muslim Girls College, Multan",
  "Muslim Public Schools and College, Kohistan",
  "Navigator College, Thatta",
  "Navigator, Sujawal",
  "Navigator, Thatta",
  "Nazareth Girls Degree College (Hyderabad)",
  "NCLS, Islamabad",
  "NCR-CET College, Karachi",
  "Nixor College, Karachi",
  "NJV Govt. Higher Secondary School, Karachi",
  "Non, Baden",
  "Nowshera Punjab College Nowshera",
  "NUML, Multan",
  "Nusrat Jahan Girls College, Chiniot",
  "OPF College (Islamabad)",
  "Option not available, Hyderabad",
  "Orbit College Thandkoi (Swabi)",
  "Other, Other",
  "Oxford Grammar Public H/S School Pangrio Badin, Hyderabad",
  "Oxford Group of School and College Kohat (Kohat)",
  "PAF Chapter, Karachi",
  "Pak-Turk International Schools and Colleges - Rawalpindi",
  "Pak-Turk International Schools and Colleges, Attock",
  "Pak-Turk International Schools and Colleges, Hyderabad",
  "Pak-Turk International Schools and Colleges, Islamabad",
  "Pak-Turk International Schools and Colleges, Karachi",
  "Pak-Turk International Schools and Colleges, Lahore",
  "Pakistan International Public School and Girls College - Abbottabad",
  "Pakistan Shipowners Govt. College, Karachi",
  "Paras Science College Kandiaro, Karachi",
  "Peace College Mardan, Mardan",
  "Peace College, Abbottabad",
  "Peace Group of Schools and Colleges, Haripur",
  "Peace School and College",
  "Pearl College Hakimabad Nowshera (Malakand)",
  "Pearl College, Nowshera",
  "PECHS COLLEGE FOR WOMEN (Karachi)",
  "Perfect School (Thatta)",
  "Peshawar Lahore Grammar School",
  "Peshawar Model Degree College (Peshawar)",
  "PGC Bhalwal (Sargodha)",
  "PGC FSD - Faisalabad",
  "PGC Kot Addu - Zhob, Zhob",
  "PGC Nowshera, Mardan",
  "PGC Okara (Okara)",
  "PGC Rawalakot, Rawalakot",
  "PGC Sahiwal, SGD",
  "PGC, Faisalabad",
  "PGC, Sheikhupura",
  "Phoenix Higher Secondary College, Hyderabad",
  "PIPS, Abbottabad",
  "PKICS, Mirpur",
  "PMDC, Peshawar",
  "PNL, Sukkur",
  "Progressive Public School, Baden",
  "Public School and College - Sargodha",
  "Public School and College Jutial Gilgit, Islamabad",
  "public school hyderabad (Hyderabad)",
  "Public School Hyderabad (Thatta)",
  "Public School Sukkur (Sukkur)",
  "Punjab college (Gujranwala)",
  "Punjab College (Islamabad)",
  "Punjab College (Lahore)",
  "Punjab College (Multan)",
  "Punjab College (Pirmahal)",
  "Punjab College - Faisalabad, Faisalabad",
  "Punjab College - Rahim Yar Khan, Rahim Yar Khan",
  "Punjab College Bahawalpur (Bahawalpur)",
  "Punjab College for Women, Faisalabad",
  "Punjab College Mardan, Mardan",
  "Punjab College PDKhan, Jhelum",
  "Punjab College Sheikhupura, Sheikhupura",
  "Punjab College, Faisalabad",
  "Punjab College, Gujranwala",
  "Punjab College, Hafizabad",
  "Punjab College, Layyah",
  "Punjab College, Okara",
  "Punjab College, Peshawar",
  "Punjab College, Sialkot",
  "Punjab Girls Inter College, Muzaffar Garh",
  "Punjab Group of College, Bahawalpur",
  "Punjab Group of Colleges",
  "Punjab Group of Colleges - Rahim Yar Khan, Rahim Yar Khan",
  "Punjab Group of Colleges - Rawalpindi",
  "Punjab Group of Colleges - Sadiqabad",
  "Punjab Group of Colleges - Sialkot",
  "Punjab Group of Colleges, Abbottabad",
  "Punjab Group of Colleges, Bahawalnagar",
  "Punjab Group of Colleges, Bahawalpur",
  "Punjab Group of Colleges, Bhakkar",
  "Punjab Group of Colleges, Bhalwal",
  "Punjab Group of Colleges, Burewala",
  "Punjab Group of Colleges, Daska",
  "Punjab Group of Colleges, Dera Ghazi Khan",
  "Punjab Group of Colleges, Dera Ismail Khan",
  "Punjab Group of Colleges, Faisalabad",
  "Punjab Group of Colleges, Girdan",
  "Punjab Group of Colleges, Gujranwala",
  "Punjab Group of Colleges, Gujrat",
  "Punjab Group of Colleges, Islamabad",
  "Punjab Group of Colleges, Khushab",
  "Punjab Group of Colleges, Lahore",
  "Punjab Group of Colleges, Mardan",
  "Punjab Group of Colleges, Mirpur",
  "Punjab Group of Colleges, Multan",
  "Punjab Group of Colleges, Muzaffar Garh",
  "Punjab Group of Colleges, Nowshera",
  "Punjab Group of Colleges, Okara",
  "Punjab Group of Colleges, Rahim Yar Khan",
  "Punjab Group of Colleges, Rajan Pur",
  "Punjab Group of Colleges, Rawalpindi",
  "Punjab Group of Colleges, Safdar Abad (Dhaban Singh)",
  "Punjab Group of Colleges, Sahiwal",
  "Punjab Group of Colleges, Sargodha",
  "Punjab Group of Colleges, Sialkot",
  "Punjab Group of Colleges, Sukkur",
  "Punjab Group of Colleges, Vehari",
  "Punjab Group of Colleges, Wazirabad",
  "QAED College - Dera Ghazi Khan",
  "Qamar-e-Bani Hashim Higher Secondary School (Karachi)",
  "QMC, Lahore",
  "Quaid Azam College, Bannu",
  "Quaid e (Swabi)",
  "Quaid e Azam College, Mardan",
  "Quaid-e-Azam College, Mardan",
  "Quaid-e-Azam Rangers School and College Hyderabad, Hyderabad",
  "Quaid-e-Azam, Mardan",
  "Quaid-e-Azam, Swabi",
  "Quaideazam, Gujranwala",
  "Quality Schools and College - Lahore",
  "Quetta (Please provide more information)",
  "Quetta Beaconhouse School",
  "Quetta Garrison Academy, Quetta",
  "Quetta Govt Science College, Quetta",
  "Quetta Govt. Girls Degree College Quetta",
  "Qurtaba College, Peshawar",
  "Qurtuba School and College (Dera Ismail Khan)",
  "Rahim Public College, Baden",
  "Rawalpindi International",
  "Rawalpindi Punjab Group of Colleges",
  "Read Foundation College Bhimber, Bhimber",
  "Reader College - Sargodha",
  "Reader Group of College, Rawalpindi",
  "Reader Group of College, Sargodha",
  "Riaz Government Girls College (Karachi)",
  "Roots Faisalabad (Faisalabad)",
  "Roots Millennium College, Islamabad",
  "Roots Millennium College, Karachi (Rawalpindi)",
  "Roots Millennium College, Lahore",
  "Roots Millennium School, Khyber Campus, Peshawar",
  "Roshan Tara Higher Secondary School Kashmore, Kashmor",
  "Roshni Institution of Scenic, Tando Bago",
  "Royal College Narowal, Sialkot",
  "Royal National College Kharian, Gujrat",
  "RYK - Rahim Yar Khan",
  "S.F Govt: Boys Degree College Mithi, Mithi",
  "S.M. Govt. Science College (Karachi)",
  "Sachal Sarmast Degree College Ranipur, Khairpur",
  "Sachal Sarmast Degree College Ranipur, Ranipur",
  "Sadiq Public School, Bahawalpur",
  "Sadiqabad Punjab Group of Colleges",
  "Sadique Faqeer Degree College Mithi, Mithi",
  "Saint Lawrence Government Girls Degree College - Karachi",
  "Saint Lawrence Govt Girls college (Karachi)",
  "Sajjad Model Higher Secondary School Khairpur, Khairpur",
  "Sakims, Multan",
  "Sakrand Govt. Girls College Sakrand",
  "Sakrand Govt. Girls Degree College",
  "Salim Habib Higher Secondary School Toba Tek Singh, Toba Tek Singh",
  "Sarwari Islamic Government Degree Boys College (Hala)",
  "Scholars College, Karachi",
  "Scholars Science College, Wah Cantt",
  "Schollar Science College, Karachi",
  "School Convent H8/College F6, Islamabad",
  "School of Excellence, Sukkur",
  "Science Foundation (Hyderabad)",
  "Scienta Vision G/10-2 (Islamabad)",
  "Sedna school and degree college (Islamabad)",
  "Sedna school and degree college (Karachi)",
  "Shah Latif Degree College, Kamber",
  "Shaheed Benazir Bhutto Govt. Girls College, Lyari, Karachi, Wah Cantt",
  "Shaheed Muhtarma Benazir Govt Girls College, Karachi",
  "Shaheed-e-Millat Govt. College, Karachi, Karachi",
  "Shaheen Public School, Mirpur Khas",
  "Shaikh Zaid (Karachi)",
  "Shamsi Girls College, Karachi",
  "Sheikh Zayed College - Karachi",
  "Sheikh Zayed Higher Secondary School Rahim Yar Khan (Rahim Yar Khan)",
  "Sialkot Nisa Girls College",
  "Siddeeq Public School - Rawalpindi",
  "Sindh Academy Umerkot, Umarkot",
  "Sindh College, Umarkot",
  "Sindh Muslim Govt Science College, Karachi",
  "Sindh Public School and College (Umarkot)",
  "Sindh Science College, Larkana",
  "Sir Adamjee Institute (Karachi)",
  "Sir Syed Govt. Girls College, Karachi",
  "Sir Syed School (Wah Cantt)",
  "Sir Syed School and College Campus 1 / FG Post Grad, Wah Cantt",
  "Sir Syed School and College Campus 4, Wah Cantt",
  "SLS College, Islamabad",
  "SM College, Tando Adam",
  "SM Science College (Karachi)",
  "SMB Fatima Jinnah Govt College, Karachi",
  "smb.fatima.jinnah (Karachi)",
  "Spark Academy, Nawabshah",
  "SPS College Batkhela (Chakdara)",
  "SPS, Swat",
  "SPSC Umerkot, Mirpur Khas",
  "SPSC, Kotri",
  "SPSC, Mithi",
  "SPSC, Umarkot",
  "SRE Majid College",
  "SSAT College, Karachi",
  "SSAT Degree College, Karachi",
  "St Lawrence (Karachi)",
  "St. Bonaventure's High School, Hyderabad",
  "St. Joseph's College for Women (Karachi)",
  "St. Joseph's Convent School, Karachi",
  "St. Joseph's Convent School, Quetta",
  "St. Lawrence Govt. College for Women, Karachi (Karachi)",
  "St. Mary's Convent Girls Higher Secondary School, Hyderabad",
  "St. Michaels Convent School, Karachi",
  "St. Patrick College, Karachi",
  "St. Patrick's High School, Karachi",
  "Star Grammar Public High School (Karachi)",
  "Stars College Multan, Multan",
  "Step by PGC, Rawalpindi",
  "Steps Academy (Lahore)",
  "Steps College (Rawalpindi)",
  "Student's Inn - Faisalabad",
  "Sukkur Govt. Girls Higher Secondary School Barrage",
  "Sum College, Larkana",
  "Superior College (Faisalabad)",
  "Superior College - Mianwali",
  "Superior College Chiniot (Chiniot)",
  "Superior College Hyderabad (Baden)",
  "Superior College Jauharabad, Jauharabad",
  "Superior College Mandi (Mandi Bahauddin)",
  "Superior College Mian Channu, Mian Chanu",
  "Superior College of Science (Hyderabad)",
  "Superior College of Science - Hyderabad",
  "Superior College of Science, Hyderabad",
  "Superior College, Chakwal",
  "Superior College, Chichawatni",
  "Superior College, Chiniot",
  "Superior College, Islamabad",
  "Superior College, Lahore",
  "Superior College, Mian Chanu",
  "Superior College, Sargodha",
  "Superior College, Sialkot",
  "Superior College, Sujawal",
  "Superior College, Toba Tek Singh",
  "Superior Group of Colleges, Attock",
  "Superior Group of Colleges, Layyah",
  "Superior Group of Colleges, M.B.Din, Mandi Bahauddin",
  "Superior Hyderabad, Kotri",
  "Superior Science College - Lahore",
  "Superior Science College Khairpur (Khairpur)",
  "Superior Science College, Jhang",
  "Superior Science Colleges, Karachi",
  "Superior, Hyderabad",
  "Supernova, Islamabad",
  "Swabi Islamia College University Peshawar",
  "SZABIST College, Larkana",
  "SZPS, Rahim Yar Khan",
  "TABs, Hyderabad",
  "Tameer I Nau (Quetta)",
  "Tameer I Watan College, Rawalpindi",
  "Tameer I Wattan, Abbottabad",
  "Tameer-i-Nau - Karachi",
  "Tamer-e-Nou College Quetta, Quetta",
  "Tariq Bin Ziad Inter College, Sahiwal",
  "TCF School - Hyderabad",
  "Texila American University, Other",
  "Thatta Bahria Foundation College, Nazimabad",
  "The American School",
  "The Career College Ghotki Campus (Ghotki)",
  "The City School - Ghotki, Hyderabad",
  "The City School - Islamabad",
  "The City School, Bahawalpur",
  "The City School, Karachi",
  "The City School, Lahore",
  "The City School, Mirpur Khas",
  "The City School, Okara",
  "The City School, Quetta",
  "The City School, Sialkot",
  "The Concept College - Hyderabad",
  "The Concept School, Thatta",
  "The Crescent College (Lahore)",
  "The Crescent School and College, Other",
  "The Educators Larkana Campus (Larkana)",
  "The Educators/ KIPS College (Lahore)",
  "The Excellence School and College Pano Akil, Sukkur",
  "The Hope Science School and College, Islamabad",
  "The Indus Academy, Quetta",
  "The International School of Choueifat, Lahore",
  "The Learning Academy, Islamabad",
  "The Lyceum A-Levels, Karachi",
  "The Navigator Science School and College, Thatta",
  "The QPS Swabi, Swabi",
  "The Scholars Science College, Wah Cantt",
  "TSSC, Wah Cantt",
  "Tufail Shaheed College, Mardan",
  "Umarkot Degree Boys College, Umarkot",
  "Unique Group of Institutions",
  "University Public School, Adezai",
  "Uswa College Islamabad (Abbottabad)",
  "Wapda Degree College Guddu, Kashmor",
  "Waqar Public School - Khairpur",
  "Warsak Model School and College, Peshawar",
  "Wensam College, Dera Ismail Khan",
  "Whales College, Karachi",
  "White House Grammar School (Karachi)",
  "Wisdom, Karak City",
  "Women's, Karachi",
  "Worker College, Hyderabad",
  "Zavia Science College - Rawalpindi",
  "Ziauddin Intermediate College, Karachi",
  "Zubaida College, Hyderabad",
  " ",
];

export const schoolsOld = [
  "Adamjee Govt. Science College, Karachi",
  "Islamia Govt. Science College, Karachi",
  "Govt. PECHS Education Foundation Science College, Karachi",
  "Govt. Degree Science & Commerce College, Gulshan-e-Iqbal, Karachi",
  "Govt. Degree Boys College, Gulzar-e-Hijri, Karachi",
  "Govt. National College, Karachi",
  "Govt. Degree Boys College, Gulistan-e-Jauhar, Karachi",
  "Govt. Jamia Millia Degree College, Karachi",
  "Govt. Superior Science College, Karachi",
  "Govt. Boys Inter College, Landhi, Karachi",
  "Allama Iqbal Govt. – Boys Science College, Karachi",
  "Govt Degree College, Malir Cantt, Karachi",
  "ARG Govt. Degree Boys College, Landhi, Quaidabad, Karachi",
  "Govt. Degree College Murad Memon Goth, Karachi",
  "Govt. Degree Boys College, Korangi, Karachi",
  "D.J Sindh Govt. Science College, Karachi",
  "S.M. Govt. Science College, Shahrah-e-Liaquat, Karachi",
  "Govt. Aisha Bawani College, Karachi",
  "Govt. Degree Science & Commerce College, Lyari, Karachi",
  "Haji Abdullah Haroon Govt. College, Karachi",
  "Govt. Delhi Inter Science College",
  "Govt. City College Musa Colony, Karachi",
  "Govt. Degree Science College, Liaquatabad, Karachi",
  "Govt. Sirajud Daula Degree College, Karachi",
  "Pakistan Shipowners Govt. College, Karachi",
  "Govt. Degree Boys College, North Karachi, Karachi",
  "Govt Degree Boys College, North Karachi",
  "Govt. Degree Boys College, Mangopir, Karachi",
  "Govt. Degree Boys College, Konkar, Karachi",
  "Govt. Degree Boys College, Surjani Town, Karachi",
  "Govt. Degree Boys College, New Karachi, Karachi",
  "Govt. Degree Boys College, Buffer Zone, Karachi",
  "Govt. Jinnah College, Nazimabad, Karachi",
  "Govt. Degree Science & Commerce College, Orangi Town, Karachi",
  "Govt. Degree Boys College Asifabad, Karachi",
  "Govt. Degree Boys College, Keamari, Karachi",
  "Govt. College For Men, Nazimabad, Karachi",
  "Govt. Degree Boys College, Shams Pir, Karachi",
  "Govt. Degree Boys College, Baldia Town, Karachi",
  "Govt. Degree Boys College,  KMC Store NIshter Road, Karachi",
  "Begum Nusrat Bhutto Govt. Boys College, Lyari, Karachi",
  "Govt. Degree Boys College, Ibrahim Hyderi, Karachi",
  "Govt. Boys H.S.S. Kamal Khan Jokhio, Karachi",
  "Ghazi Muhammad Bin Qasim H.S.S. Agra Taj Colony Chak,",
  "Allama Iqbal Govt. Boys H.S.S., Block 16, FB Area Karachi",
  "Govt. Comprehensive H.S.S, Korangi-0.3, Karachi",
  "Govt. Boys Comprehensive H.S.S., Azizabad, Karachi",
  "Govt. Boys H.S.S. No. 2 K, Area Korangi, Karachi",
  "Govt. Mumtaz Boys H.S.S. Landhi, Karachi",
  "Govt. Boys H.S.S. Konkar Village Malir Karachi",
  "Abdullah Govt. College for Women, Karachi",
  "Govt. College for Women, Nazimabad, Karachi",
  "Sir Syed Govt. Girls College, Karachi",
  "APWA Govt. College for Women, Karachi",
  "Shaheed-e-Millat Govt. Degree Girls College, Azizabad, Karachi",
  "Govt. Degree Girls College, Al-Noor, FB Area, Karachi",
  "Riaz Govt. Girls College, Liaquatabad, Karachi",
  "Govt. Degree College for Women, Nazimabad, Karachi",
  "Govt. Girls Degree College, North Karachi",
  "Govt. Girls Degree College, Nazimabad, Karachi",
  "Govt. College for Women, New Karachi, Karachi",
  "Govt. Girls Inter College Orangi Sector, Karachi",
  "Govt. Degree Girls College, Orangi, Karachi",
  "Govt. Girls College, Metroville SITE, Karachi",
  "Govt. College for Women, Shahrah-e-Liaquat, Karachi",
  "Govt. Inter Girls College, Lyari, Karachi",
  "Govt. Karachi College for Women, Chand Bibi Road, Karachi",
  "Govt. SMB Fatima Jinnah Girls College, Karachi",
  "Govt. Girls Degree College Zamzama, Karachi",
  "Govt. College for Women, Korangi 06, Karachi",
  "Govt, College for Women, Korangi-4, Karachi",
  "Govt. Girls Degree College, Korangi, Karachi",
  "Govt Degree Girls College, Ibrahim Hydri, Karachi",
  "Govt. College for Women Saudabad, Karachi",
  "Govt. Girls Science College, Shah Faisal Colony, Karachi",
  "Allama Iqbal Govt. Girls College, Shah Faisal Colony No. 3, Karachi",
  "Liaquat Govt. Girls College Malir, Karachi",
  "Govt. Degree College Malir Cantt, Karachi",
  "Govt. Girls College, Landhi, Karachi",
  "Govt. Girls College, PIB Colony, Karachi",
  "St. Lawrance Govt. College for Women, Karachi",
  "Govt. Degree Girls College, Lines Area, Karachi",
  "Bamm PECHS Govt. College for Women, Karachi",
  "Khatoon-e-Pakistan Government College for Women, Stadium Road",
  "Govt. Degree College for Boys and Girls Stadium Road, Karachi",
  "Govt. Degree Science and Commerce College, Gulshan-e-Iqbal, Karachi",
  "Govt. Girls Degree College, Mehmoodabad, Karachi",
  "Govt. Degree Girls College, Safora Goth, Gulistan-e-Jauhar, Karachi",
  "Govt. Degree Girls College, Pak Colony, Karachi",
  "Govt. Degree Girls College, Buffer Zone, Karachi",
  "Jan Muhammad Brohi Govt. Degree Girls College, Gulshah-e- Maymar, Karachi",
  "Govt. Degree Girls College, Surjani Town, Karachi",
  "Govt. Degree Girls College, Shahnawaz Shar Goth, Karachi",
  "Govt. Girls Degree College, Gulzar-e-Hijri, Karachi",
  "Marium Mukhtiar Govt. Girls Degree College, Liaquatabad, Karachi",
  "Bibi Asifa Govt. Girls College, Muzaffarabad, Landhi, Karachi",
  "Shaheed Benazir Bhutto Govt. Girls College, Lyari, Karachi",
  "Govt. Girls College, Sharrafi Goth, Karachi",
  "Govt. Girls H.S.S. Landhi, Karachi",
  "Govt. Comprehensive H.S.S, North Nazimabad, Karachi",
  "Govt. Girls H.S.S. Bhiro Village, Karachi",
  "APWA Govt. Girls H.S.S., Liaquatabad, Karachi",
  "PAF Govt. Girls H.S.S. Karachi",
  "Govt. Girls H.S.S. Green Belt, Karachi",
  "Khaldunia Public School, Islamabad",
  "The City School",
  "Bahria College",
  "Cadet College, Hassanabdal",
  "Army Public School",
  "Beaconhouse School",
  "Lahore Grammar School",
  "Nixor A-Levels",
  "Karachi Grammar School",
  "The Lyceum A-Levels",
  "Cedar A-Levels",
  "Cordoba School for A-Levels",
  "Dawood Public School A-Levels",
  "Aisha Bawany Academy",
  "Karachi Public School",
  "Pak-Turk International Schools and Colleges",
  "Bahria Foundation College, Nazimabad",
  "Foundation Public School",
  "St. Michaels Convent School",
  "St. Joseph’s Convent School",
  "Habib Public School",
  "Hamdard Public School",
  "Garrison Academy",
  "St. Anthony’s College",
  "St. Patrick’s High School",
  "St. Peter’s High School",
  "Progressive Public School",
  "DA Public School",
  "White House Grammar School",
  "Generation’s School",
  "The Avicenna School",
  "Froebel Education Centre",
  "Washington International School",
  "L’ecole for Advance Studies",
  "Karachi Cadet School",
  "Falconhouse Grammar School",
  "The OASYS School",
  "Westminster School & College",
  "Aitchison Model School",
  "Jaffar Public School",
  "K N Academy",
  "Ladybird Grammar School",
  "The American School",
  "Happy Home School",
  "Shaheen Public School",
  "Southshore School for A-Level Studies",
  "The Indus Academy",
  "Usman Public School",
  "The A.M.I School",
  "Anees Hussain, Karachi",
  "Meritorious Science College, Karachi",
  "Roots Millennium College, Karachi",
  "Dar-e-Arqam Schools",
  "Sadiq Public School",
  "Kinnaird College",
  "COMMECS College",
  "NCR-CET College",
  "Fazaia Inter College",
  "DHACSS Shaikh Khalifa Bin Zayed Campus",
  "Punjab Group of Colleges",
  "Private Intermediate",
  "Private A-Levels",
  "Allied School",
  "TCF School",
];
export const cities = [
  "Abbottabad",
  "Adilpur",
  "Ahmadpur East",
  "Ahmadpur Sial",
  "Akora",
  "Aliabad",
  "Alik Ghund",
  "Alipur",
  "Alizai",
  "Alpurai",
  "Aman Garh",
  "Amirabad",
  "Arifwala",
  "Ashanagro Koto",
  "Athmuqam",
  "Attock City",
  "Awaran",
  "Baddomalhi",
  "Badin",
  "Baffa",
  "Bagarji",
  "Bagh",
  "Bahawalnagar",
  "Bahawalnagar",
  "Bahawalpur",
  "Bakhri Ahmad Khan",
  "Bandhi",
  "Bannu",
  "Barishal",
  "Barkhan",
  "Basirpur",
  "Basti Dosa",
  "Bat Khela",
  "Battagram",
  "Begowala",
  "Bela",
  "Berani",
  "Bhag",
  "Bhakkar",
  "Bhalwal",
  "Bhan",
  "Bhawana",
  "Bhera",
  "Bhimbar",
  "Bhiria",
  "Bhit Shah",
  "Bhopalwala",
  "Bozdar Wada",
  "Bulri",
  "Burewala",
  "Chak",
  "Chak Azam Sahu",
  "Chak Five Hundred Seventy-five",
  "Chak Jhumra",
  "Chak One Hundred Twenty Nine Left",
  "Chak Thirty-one -Eleven Left",
  "Chak Two Hundred Forty-nine Thal Development Authority",
  "Chakwal",
  "Chaman",
  "Chamber",
  "Charsadda",
  "Chawinda",
  "Chenab Nagar",
  "Cherat Cantonement",
  "Chhor",
  "Chichawatni",
  "Chilas",
  "Chiniot",
  "Chishtian",
  "Chitral",
  "Choa Saidan Shah",
  "Chowki Jamali",
  "Chuchar-kana Mandi",
  "Chuhar Jamali",
  "Chunian",
  "Dadhar",
  "Dadu",
  "Daggar",
  "Daira Din Panah",
  "Dajal",
  "Dalbandin",
  "Dandot RS",
  "Daromehar",
  "Darya Khan",
  "Darya Khan Marri",
  "Daska Kalan",
  "Dasu",
  "Daud Khel",
  "Daulatpur",
  "Daultala",
  "Daur",
  "Dera Allahyar",
  "Dera Bugti",
  "Dera Ghazi Khan",
  "Dera Ismail Khan",
  "Dera Murad Jamali",
  "Dhanot",
  "Dhaunkal",
  "Dhoro Naro",
  "Digri",
  "Dijkot",
  "Dinan Bashnoian Wala",
  "Dinga",
  "Dipalpur",
  "Diplo",
  "Doaba",
  "Dokri",
  "Duki",
  "Dullewala",
  "Dunga Bunga",
  "Dunyapur",
  "Eidgah",
  "Eminabad",
  "Faisalabad",
  "Faqirwali",
  "Faruka",
  "Fazilpur",
  "Fort Abbas",
  "Gadani",
  "Gakuch",
  "Gambat",
  "Gandava",
  "Garh Maharaja",
  "Garhi Khairo",
  "Garhiyasin",
  "Gharo",
  "Ghauspur",
  "Ghotki",
  "Gilgit",
  "Gojra",
  "Goth Garelo",
  "Goth Phulji",
  "Goth Radhan",
  "Gujar Khan",
  "Gujranwala",
  "Gujrat",
  "Gulishah Kach",
  "Gwadar",
  "Hadali",
  "Hafizabad",
  "Hala",
  "Hangu",
  "Haripur",
  "Harnai",
  "Harnoli",
  "Harunabad",
  "Hasilpur",
  "Hattian Bala",
  "Haveli Lakha",
  "Havelian",
  "Hazro City",
  "Hingorja",
  "Hujra Shah Muqim",
  "Hyderabad",
  "Islamabad",
  "Islamkot",
  "Jacobabad",
  "Jahanian Shah",
  "Jalalpur Jattan",
  "Jalalpur Pirwala",
  "Jampur",
  "Jamshoro",
  "Jand",
  "Jandiala Sher Khan",
  "Jaranwala",
  "Jati",
  "Jatoi Shimali",
  "Jauharabad",
  "Jhang City",
  "Jhang Sadr",
  "Jhawarian",
  "Jhelum",
  "Jhol",
  "Jiwani",
  "Johi",
  "Jam Sahib",
  "Kabirwala",
  "Kadhan",
  "Kahna Nau",
  "Kahror Pakka",
  "Kahuta",
  "Kakad Wari Dir Upper",
  "Kalabagh",
  "Kalaswala",
  "Kalat",
  "Kaleke Mandi",
  "Kallar Kahar",
  "Kalur Kot",
  "Kamalia",
  "Kamar Mushani",
  "Kambar",
  "Kamoke",
  "Kamra",
  "Kandhkot",
  "Kandiari",
  "Kandiaro",
  "Kanganpur",
  "Karachi",
  "Karak",
  "Karaundi",
  "Kario Ghanwar",
  "Karor",
  "Kashmor",
  "Kasur",
  "Keshupur",
  "Keti Bandar",
  "Khadan Khak",
  "Khadro",
  "Khairpur",
  "Khairpur Mirs",
  "Khairpur Nathan Shah",
  "Khairpur Tamewah",
  "Khalabat",
  "Khandowa",
  "Khanewal",
  "Khangah Dogran",
  "Khangarh",
  "Khanpur",
  "Khanpur Mahar",
  "Kharan",
  "Kharian",
  "Khewra",
  "Khurrianwala",
  "Khushab",
  "Khuzdar",
  "Kohat",
  "Kohlu",
  "Kot Addu",
  "Kot Diji",
  "Kot Ghulam Muhammad",
  "Kot Malik Barkhurdar",
  "Kot Mumin",
  "Kot Radha Kishan",
  "Kot Rajkour",
  "Kot Samaba",
  "Kot Sultan",
  "Kotli",
  "Kotli Loharan",
  "Kotri",
  "Kulachi",
  "Kundian",
  "Kunjah",
  "Kunri",
  "Lachi",
  "Ladhewala Waraich",
  "Lahore",
  "Lakhi",
  "Lakki",
  "Lala Musa",
  "Lalian",
  "Landi Kotal",
  "Larkana",
  "Layyah",
  "Liliani",
  "Lodhran",
  "Loralai",
  "Mach",
  "Madeji",
  "Mailsi",
  "Malakand",
  "Malakwal",
  "Malakwal City",
  "Malir Cantonment",
  "Mamu Kanjan",
  "Mananwala",
  "Mandi Bahauddin",
  "Mangla",
  "Mankera",
  "Mansehra",
  "Mardan",
  "Mastung",
  "Matiari",
  "Matli",
  "Mehar",
  "Mehmand Chak",
  "Mehrabpur",
  "Mian Channun",
  "Mianke Mor",
  "Mianwali",
  "Minchianabad",
  "Mingora",
  "Miran Shah",
  "Miro Khan",
  "Mirpur Bhtoro",
  "Mirpur Khas",
  "Mirpur Mathelo",
  "Mirpur Sakro",
  "Mirwah Gorchani",
  "Mitha Tiwana",
  "Mithi",
  "Moro",
  "Moza Shahwala",
  "Multan",
  "Muridke",
  "Murree",
  "Musa Khel Bazar",
  "Mustafabad",
  "Muzaffargarh",
  "Muzaffarabad",
  "Nabisar",
  "Nankana Sahib",
  "Narang Mandi",
  "Narowal",
  "Nasirabad",
  "Naudero",
  "Naukot",
  "Naushahra Virkan",
  "Naushahro Firoz",
  "Nawabshah",
  "Nazir Town",
  "New Mirpur",
  "Noorabad",
  "Nowshera",
  "Nowshera Cantonment",
  "Nushki",
  "Okara",
  "Ormara",
  "Pabbi",
  "Pad Idan",
  "Paharpur",
  "Pakpattan",
  "Panjgur",
  "Pano Aqil",
  "Parachinar",
  "Pasni",
  "Pasrur",
  "Pattoki",
  "Peshawar",
  "Phalia",
  "Pind Dadan Khan",
  "Pindi Bhattian",
  "Pindi Gheb",
  "Pir Jo Goth",
  "Pir Mahal",
  "Pishin",
  "Pithoro",
  "Qadirpur Ran",
  "Qila Abdullah",
  "Qila Saifullah",
  "Quetta",
  "Rahim Yar Khan",
  "Raiwind",
  "Raja Jang",
  "Rajanpur",
  "Rajo Khanani",
  "Ranipur",
  "Rasulnagar",
  "Ratodero",
  "Rawala Kot",
  "Rawalpindi",
  "Renala Khurd",
  "Risalpur Cantonment",
  "Rohri",
  "Rojhan",
  "Rustam",
  "Saddiqabad",
  "Sahiwal",
  "Sahiwal",
  "Saidu Sharif",
  "Sakrand",
  "Samaro",
  "Sambrial",
  "Sanghar",
  "Sangla Hill",
  "Sanjwal",
  "Sann",
  "Sarai Alamgir",
  "Sarai Naurang",
  "Sarai Sidhu",
  "Sargodha",
  "Sehwan",
  "Setharja Old",
  "Shabqadar",
  "Shahdad Kot",
  "Shahdadpur",
  "Shahkot",
  "Shahpur",
  "Shahpur Chakar",
  "Shahr Sultan",
  "Shakargarh",
  "Sharqpur Sharif",
  "Shekhupura",
  "Shikarpur",
  "Shingli Bala",
  "Shinpokh",
  "Shorkot",
  "Shujaabad",
  "Sialkot",
  "Sibi",
  "Sillanwali",
  "Sinjhoro",
  "Skardu",
  "Sobhodero",
  "Sodhri",
  "Sohbatpur",
  "Sukheke Mandi",
  "Sukkur",
  "Surab",
  "Surkhpur",
  "Swabi",
  "Sita Road",
  "Talagang",
  "Talamba",
  "Talhar",
  "Tandlianwala",
  "Tando Adam",
  "Tando Allahyar",
  "Tando Bago",
  "Tando Jam",
  "Tando Mitha Khan",
  "Tando Muhammad Khan",
  "Tangi",
  "Tangwani",
  "Tank",
  "Taunsa",
  "Thal",
  "Tharu Shah",
  "Thatta",
  "Thul",
  "Timargara",
  "Toba Tek Singh",
  "Topi",
  "Turbat",
  "Ubauro",
  "Umarkot",
  "Upper Dir",
  "Usta Muhammad",
  "Uthal",
  "Utmanzai",
  "Vihari",
  "Wana",
  "Warah",
  "Wazirabad",
  "Yazman",
  "Zafarwal",
  "Zahir Pir",
  "Zaida",
  "Zhob",
  "Ziarat",
];

export const countries = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "Andorra",
  "Angola",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bhutan",
  "Bolivia",
  "Bosnia and Herzegovina",
  "Botswana",
  "Brazil",
  "Brunei",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cabo Verde",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Colombia",
  "Comoros",
  "Congo",
  "Costa Rica",
  "Croatia",
  "Cuba",
  "Cyprus",
  "Czech Republic",
  "Democratic Republic of the Congo",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "East Timor",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Eswatini",
  "Ethiopia",
  "Fiji",
  "Finland",
  "France",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Greece",
  "Grenada",
  "Guatemala",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Honduras",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Israel",
  "Italy",
  "Ivory Coast",
  "Jamaica",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Kosovo",
  "Kuwait",
  "Kyrgyzstan",
  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Macedonia",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Mauritania",
  "Mauritius",
  "Mexico",
  "Micronesia",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "North Korea",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestine",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Qatar",
  "Romania",
  "Russia",
  "Rwanda",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Korea",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Sweden",
  "Switzerland",
  "Syria",
  "Taiwan",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Togo",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States of America",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Vatican City",
  "Venezuela",
  "Vietnam",
  "Yemen",
  "Zambia",
  "Zimbabwe",
];
